# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouYu_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYu_Project

  pod "Kingfisher"
  pod "SnapKit"
  pod "R.swift"
pod 'Alamofire'
pod 'HandyJSON'
pod 'SwiftyJSON'



end
